apiVersion: v1
kind: Service
metadata:
  name: website-svc
spec:
  selector:
    app: website
  type: NodePort         # Use LoadBalancer if youâ€™re on a managed cloud
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30012      # Fixed NodePort; omit for dynamic assignment
